import React, {useState, useRef, useEffect} from 'react';
import styles from '../styles/components/countryPicker.module.css';
import * as Flags from 'country-flag-icons/react/3x2';
import { hasFlag } from 'country-flag-icons'

export function CountryPicker(props) {
  const { onChange, value } = props;
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    if (!value) {
      setVisible(false);
    }
  }, [value])

  const flagComponents = [
  <Flags.AF onClick={() => handleOnClick(<Flags.AF />)} />,
 <Flags.AL onClick={() => handleOnClick(<Flags.AL />)} />,
 <Flags.DZ onClick={() => handleOnClick(<Flags.DZ />)} />,
 <Flags.AS onClick={() => handleOnClick(<Flags.AS />)} />,
 <Flags.AD onClick={() => handleOnClick(<Flags.AD />)} />,
 <Flags.AO onClick={() => handleOnClick(<Flags.AO />)} />,
 <Flags.AI onClick={() => handleOnClick(<Flags.AI />)} />,
 <Flags.AQ onClick={() => handleOnClick(<Flags.AQ />)} />,
 <Flags.AG onClick={() => handleOnClick(<Flags.AG />)} />,
 <Flags.AR onClick={() => handleOnClick(<Flags.AR />)} />,
 <Flags.AM onClick={() => handleOnClick(<Flags.AM />)} />,
 <Flags.AW onClick={() => handleOnClick(<Flags.AW />)} />,
 <Flags.AU onClick={() => handleOnClick(<Flags.AU />)} />,
 <Flags.AT onClick={() => handleOnClick(<Flags.AT />)} />,
 <Flags.AZ onClick={() => handleOnClick(<Flags.AZ />)} />,
 <Flags.BS onClick={() => handleOnClick(<Flags.BS />)} />,
 <Flags.BH onClick={() => handleOnClick(<Flags.BH />)} />,
 <Flags.BD onClick={() => handleOnClick(<Flags.BD />)} />,
 <Flags.BB onClick={() => handleOnClick(<Flags.BB />)} />,
 <Flags.BY onClick={() => handleOnClick(<Flags.BY />)} />,
 <Flags.BE onClick={() => handleOnClick(<Flags.BE />)} />,
 <Flags.BZ onClick={() => handleOnClick(<Flags.BZ />)} />,
 <Flags.BJ onClick={() => handleOnClick(<Flags.BJ />)} />,
 <Flags.BM onClick={() => handleOnClick(<Flags.BM />)} />,
 <Flags.BT onClick={() => handleOnClick(<Flags.BT />)} />,
 <Flags.BO onClick={() => handleOnClick(<Flags.BO />)} />,
 <Flags.BA onClick={() => handleOnClick(<Flags.BA />)} />,
 <Flags.BW onClick={() => handleOnClick(<Flags.BW />)} />,
 <Flags.BV onClick={() => handleOnClick(<Flags.BV />)} />,
 <Flags.BR onClick={() => handleOnClick(<Flags.BR />)} />,
 <Flags.IO onClick={() => handleOnClick(<Flags.IO />)} />,
 <Flags.BN onClick={() => handleOnClick(<Flags.BN />)} />,
 <Flags.BG onClick={() => handleOnClick(<Flags.BG />)} />,
 <Flags.BF onClick={() => handleOnClick(<Flags.BF />)} />,
 <Flags.BI onClick={() => handleOnClick(<Flags.BI />)} />,
 <Flags.KH onClick={() => handleOnClick(<Flags.KH />)} />,
 <Flags.CM onClick={() => handleOnClick(<Flags.CM />)} />,
 <Flags.CA onClick={() => handleOnClick(<Flags.CA />)} />,
 <Flags.CV onClick={() => handleOnClick(<Flags.CV />)} />,
 <Flags.KY onClick={() => handleOnClick(<Flags.KY />)} />,
 <Flags.CF onClick={() => handleOnClick(<Flags.CF />)} />,
 <Flags.TD onClick={() => handleOnClick(<Flags.TD />)} />,
 <Flags.CL onClick={() => handleOnClick(<Flags.CL />)} />,
 <Flags.CN onClick={() => handleOnClick(<Flags.CN />)} />,
 <Flags.CX onClick={() => handleOnClick(<Flags.CX />)} />,
 <Flags.CC onClick={() => handleOnClick(<Flags.CC />)} />,
 <Flags.CO onClick={() => handleOnClick(<Flags.CO />)} />,
 <Flags.KM onClick={() => handleOnClick(<Flags.KM />)} />,
 <Flags.CG onClick={() => handleOnClick(<Flags.CG />)} />,
 <Flags.CD onClick={() => handleOnClick(<Flags.CD />)} />,
 <Flags.CK onClick={() => handleOnClick(<Flags.CK />)} />,
 <Flags.CR onClick={() => handleOnClick(<Flags.CR />)} />,
 <Flags.CI onClick={() => handleOnClick(<Flags.CI />)} />,
 <Flags.HR onClick={() => handleOnClick(<Flags.HR />)} />,
 <Flags.CU onClick={() => handleOnClick(<Flags.CU />)} />,
 <Flags.CY onClick={() => handleOnClick(<Flags.CY />)} />,
 <Flags.CZ onClick={() => handleOnClick(<Flags.CZ />)} />,
 <Flags.DK onClick={() => handleOnClick(<Flags.DK />)} />,
 <Flags.DJ onClick={() => handleOnClick(<Flags.DJ />)} />,
 <Flags.DM onClick={() => handleOnClick(<Flags.DM />)} />,
 <Flags.DO onClick={() => handleOnClick(<Flags.DO />)} />,
 <Flags.EC onClick={() => handleOnClick(<Flags.EC />)} />,
 <Flags.EG onClick={() => handleOnClick(<Flags.EG />)} />,
 <Flags.SV onClick={() => handleOnClick(<Flags.SV />)} />,
 <Flags.GQ onClick={() => handleOnClick(<Flags.GQ />)} />,
 <Flags.ER onClick={() => handleOnClick(<Flags.ER />)} />,
 <Flags.EE onClick={() => handleOnClick(<Flags.EE />)} />,
 <Flags.ET onClick={() => handleOnClick(<Flags.ET />)} />,
 <Flags.FK onClick={() => handleOnClick(<Flags.FK />)} />,
 <Flags.FO onClick={() => handleOnClick(<Flags.FO />)} />,
 <Flags.FJ onClick={() => handleOnClick(<Flags.FJ />)} />,
 <Flags.FI onClick={() => handleOnClick(<Flags.FI />)} />,
 <Flags.FR onClick={() => handleOnClick(<Flags.FR />)} />,
 <Flags.GF onClick={() => handleOnClick(<Flags.GF />)} />,
 <Flags.PF onClick={() => handleOnClick(<Flags.PF />)} />,
 <Flags.TF onClick={() => handleOnClick(<Flags.TF />)} />,
 <Flags.GA onClick={() => handleOnClick(<Flags.GA />)} />,
 <Flags.GM onClick={() => handleOnClick(<Flags.GM />)} />,
 <Flags.GE onClick={() => handleOnClick(<Flags.GE />)} />,
 <Flags.DE onClick={() => handleOnClick(<Flags.DE />)} />,
 <Flags.GH onClick={() => handleOnClick(<Flags.GH />)} />,
 <Flags.GI onClick={() => handleOnClick(<Flags.GI />)} />,
 <Flags.GR onClick={() => handleOnClick(<Flags.GR />)} />,
 <Flags.GL onClick={() => handleOnClick(<Flags.GL />)} />,
 <Flags.GD onClick={() => handleOnClick(<Flags.GD />)} />,
 <Flags.GP onClick={() => handleOnClick(<Flags.GP />)} />,
 <Flags.GU onClick={() => handleOnClick(<Flags.GU />)} />,
 <Flags.GT onClick={() => handleOnClick(<Flags.GT />)} />,
 <Flags.GG onClick={() => handleOnClick(<Flags.GG />)} />,
 <Flags.GN onClick={() => handleOnClick(<Flags.GN />)} />,
 <Flags.GW onClick={() => handleOnClick(<Flags.GW />)} />,
 <Flags.GY onClick={() => handleOnClick(<Flags.GY />)} />,
 <Flags.HT onClick={() => handleOnClick(<Flags.HT />)} />,
 <Flags.HM onClick={() => handleOnClick(<Flags.HM />)} />,
 <Flags.VA onClick={() => handleOnClick(<Flags.VA />)} />,
 <Flags.HN onClick={() => handleOnClick(<Flags.HN />)} />,
 <Flags.HK onClick={() => handleOnClick(<Flags.HK />)} />,
 <Flags.HU onClick={() => handleOnClick(<Flags.HU />)} />,
 <Flags.IS onClick={() => handleOnClick(<Flags.IS />)} />,
 <Flags.IN onClick={() => handleOnClick(<Flags.IN />)} />,
 <Flags.ID onClick={() => handleOnClick(<Flags.ID />)} />,
 <Flags.IR onClick={() => handleOnClick(<Flags.IR />)} />,
 <Flags.IQ onClick={() => handleOnClick(<Flags.IQ />)} />,
 <Flags.IE onClick={() => handleOnClick(<Flags.IE />)} />,
 <Flags.IM onClick={() => handleOnClick(<Flags.IM />)} />,
 <Flags.IL onClick={() => handleOnClick(<Flags.IL />)} />,
 <Flags.IT onClick={() => handleOnClick(<Flags.IT />)} />,
 <Flags.JM onClick={() => handleOnClick(<Flags.JM />)} />,
 <Flags.JP onClick={() => handleOnClick(<Flags.JP />)} />,
 <Flags.JE onClick={() => handleOnClick(<Flags.JE />)} />,
 <Flags.JO onClick={() => handleOnClick(<Flags.JO />)} />,
 <Flags.KZ onClick={() => handleOnClick(<Flags.KZ />)} />,
 <Flags.KE onClick={() => handleOnClick(<Flags.KE />)} />,
 <Flags.KI onClick={() => handleOnClick(<Flags.KI />)} />,
 <Flags.KP onClick={() => handleOnClick(<Flags.KP />)} />,
 <Flags.KR onClick={() => handleOnClick(<Flags.KR />)} />,
 <Flags.KW onClick={() => handleOnClick(<Flags.KW />)} />,
 <Flags.KG onClick={() => handleOnClick(<Flags.KG />)} />,
 <Flags.LA onClick={() => handleOnClick(<Flags.LA />)} />,
 <Flags.LV onClick={() => handleOnClick(<Flags.LV />)} />,
 <Flags.LB onClick={() => handleOnClick(<Flags.LB />)} />,
 <Flags.LS onClick={() => handleOnClick(<Flags.LS />)} />,
 <Flags.LR onClick={() => handleOnClick(<Flags.LR />)} />,
 <Flags.LY onClick={() => handleOnClick(<Flags.LY />)} />,
 <Flags.LI onClick={() => handleOnClick(<Flags.LI />)} />,
 <Flags.LT onClick={() => handleOnClick(<Flags.LT />)} />,
 <Flags.LU onClick={() => handleOnClick(<Flags.LU />)} />,
 <Flags.MO onClick={() => handleOnClick(<Flags.MO />)} />,
 <Flags.MK onClick={() => handleOnClick(<Flags.MK />)} />,
 <Flags.MG onClick={() => handleOnClick(<Flags.MG />)} />,
 <Flags.MW onClick={() => handleOnClick(<Flags.MW />)} />,
 <Flags.MY onClick={() => handleOnClick(<Flags.MY />)} />,
 <Flags.MV onClick={() => handleOnClick(<Flags.MV />)} />,
 <Flags.ML onClick={() => handleOnClick(<Flags.ML />)} />,
 <Flags.MT onClick={() => handleOnClick(<Flags.MT />)} />,
 <Flags.MH onClick={() => handleOnClick(<Flags.MH />)} />,
 <Flags.MQ onClick={() => handleOnClick(<Flags.MQ />)} />,
 <Flags.MR onClick={() => handleOnClick(<Flags.MR />)} />,
 <Flags.MU onClick={() => handleOnClick(<Flags.MU />)} />,
 <Flags.YT onClick={() => handleOnClick(<Flags.YT />)} />,
 <Flags.MX onClick={() => handleOnClick(<Flags.MX />)} />,
 <Flags.FM onClick={() => handleOnClick(<Flags.FM />)} />,
 <Flags.MD onClick={() => handleOnClick(<Flags.MD />)} />,
 <Flags.MC onClick={() => handleOnClick(<Flags.MC />)} />,
 <Flags.MN onClick={() => handleOnClick(<Flags.MN />)} />,
 <Flags.ME onClick={() => handleOnClick(<Flags.ME />)} />,
 <Flags.MS onClick={() => handleOnClick(<Flags.MS />)} />,
 <Flags.MA onClick={() => handleOnClick(<Flags.MA />)} />,
 <Flags.MZ onClick={() => handleOnClick(<Flags.MZ />)} />,
 <Flags.MM onClick={() => handleOnClick(<Flags.MM />)} />,
 <Flags.NA onClick={() => handleOnClick(<Flags.NA />)} />,
 <Flags.NR onClick={() => handleOnClick(<Flags.NR />)} />,
 <Flags.NP onClick={() => handleOnClick(<Flags.NP />)} />,
 <Flags.NL onClick={() => handleOnClick(<Flags.NL />)} />,
 <Flags.NC onClick={() => handleOnClick(<Flags.NC />)} />,
 <Flags.NZ onClick={() => handleOnClick(<Flags.NZ />)} />,
 <Flags.NI onClick={() => handleOnClick(<Flags.NI />)} />,
 <Flags.NE onClick={() => handleOnClick(<Flags.NE />)} />,
 <Flags.NG onClick={() => handleOnClick(<Flags.NG />)} />,
 <Flags.NU onClick={() => handleOnClick(<Flags.NU />)} />,
 <Flags.NF onClick={() => handleOnClick(<Flags.NF />)} />,
 <Flags.MP onClick={() => handleOnClick(<Flags.MP />)} />,
 <Flags.NO onClick={() => handleOnClick(<Flags.NO />)} />,
 <Flags.OM onClick={() => handleOnClick(<Flags.OM />)} />,
 <Flags.PK onClick={() => handleOnClick(<Flags.PK />)} />,
 <Flags.PW onClick={() => handleOnClick(<Flags.PW />)} />,
 <Flags.PS onClick={() => handleOnClick(<Flags.PS />)} />,
 <Flags.PA onClick={() => handleOnClick(<Flags.PA />)} />,
 <Flags.PG onClick={() => handleOnClick(<Flags.PG />)} />,
 <Flags.PY onClick={() => handleOnClick(<Flags.PY />)} />,
 <Flags.PE onClick={() => handleOnClick(<Flags.PE />)} />,
 <Flags.PH onClick={() => handleOnClick(<Flags.PH />)} />,
 <Flags.PN onClick={() => handleOnClick(<Flags.PN />)} />,
 <Flags.PL onClick={() => handleOnClick(<Flags.PL />)} />,
 <Flags.PT onClick={() => handleOnClick(<Flags.PT />)} />,
 <Flags.PR onClick={() => handleOnClick(<Flags.PR />)} />,
 <Flags.QA onClick={() => handleOnClick(<Flags.QA />)} />,
 <Flags.RE onClick={() => handleOnClick(<Flags.RE />)} />,
 <Flags.RO onClick={() => handleOnClick(<Flags.RO />)} />,
 <Flags.RU onClick={() => handleOnClick(<Flags.RU />)} />,
 <Flags.RW onClick={() => handleOnClick(<Flags.RW />)} />,
 <Flags.SH onClick={() => handleOnClick(<Flags.SH />)} />,
 <Flags.KN onClick={() => handleOnClick(<Flags.KN />)} />,
 <Flags.LC onClick={() => handleOnClick(<Flags.LC />)} />,
 <Flags.PM onClick={() => handleOnClick(<Flags.PM />)} />,
 <Flags.VC onClick={() => handleOnClick(<Flags.VC />)} />,
 <Flags.WS onClick={() => handleOnClick(<Flags.WS />)} />,
 <Flags.SM onClick={() => handleOnClick(<Flags.SM />)} />,
 <Flags.ST onClick={() => handleOnClick(<Flags.ST />)} />,
 <Flags.SA onClick={() => handleOnClick(<Flags.SA />)} />,
 <Flags.SN onClick={() => handleOnClick(<Flags.SN />)} />,
 <Flags.RS onClick={() => handleOnClick(<Flags.RS />)} />,
 <Flags.SC onClick={() => handleOnClick(<Flags.SC />)} />,
 <Flags.SL onClick={() => handleOnClick(<Flags.SL />)} />,
 <Flags.SG onClick={() => handleOnClick(<Flags.SG />)} />,
 <Flags.SK onClick={() => handleOnClick(<Flags.SK />)} />,
 <Flags.SI onClick={() => handleOnClick(<Flags.SI />)} />,
 <Flags.SB onClick={() => handleOnClick(<Flags.SB />)} />,
 <Flags.SO onClick={() => handleOnClick(<Flags.SO />)} />,
 <Flags.ZA onClick={() => handleOnClick(<Flags.ZA />)} />,
 <Flags.GS onClick={() => handleOnClick(<Flags.GS />)} />,
 <Flags.SS onClick={() => handleOnClick(<Flags.SS />)} />,
 <Flags.ES onClick={() => handleOnClick(<Flags.ES />)} />,
 <Flags.LK onClick={() => handleOnClick(<Flags.LK />)} />,
 <Flags.SD onClick={() => handleOnClick(<Flags.SD />)} />,
 <Flags.SR onClick={() => handleOnClick(<Flags.SR />)} />,
 <Flags.SJ onClick={() => handleOnClick(<Flags.SJ />)} />,
 <Flags.SZ onClick={() => handleOnClick(<Flags.SZ />)} />,
 <Flags.SE onClick={() => handleOnClick(<Flags.SE />)} />,
 <Flags.CH onClick={() => handleOnClick(<Flags.CH />)} />,
 <Flags.SY onClick={() => handleOnClick(<Flags.SY />)} />,
 <Flags.TW onClick={() => handleOnClick(<Flags.TW />)} />,
 <Flags.TJ onClick={() => handleOnClick(<Flags.TJ />)} />,
 <Flags.TZ onClick={() => handleOnClick(<Flags.TZ />)} />,
 <Flags.TH onClick={() => handleOnClick(<Flags.TH />)}/>,
 <Flags.TL onClick={() => handleOnClick(<Flags.TL />)}/>,
 <Flags.TG onClick={() => handleOnClick(<Flags.TG />)}/>,
 <Flags.TK onClick={() => handleOnClick(<Flags.TK />)}/>,
 <Flags.TO onClick={() => handleOnClick(<Flags.TO />)}/>,
 <Flags.TT onClick={() => handleOnClick(<Flags.TT />)}/>,
 <Flags.TN onClick={() => handleOnClick(<Flags.TN />)}/>,
 <Flags.TR onClick={() => handleOnClick(<Flags.TR />)}/>,
 <Flags.TM onClick={() => handleOnClick(<Flags.TM />)}/>,
 <Flags.TC onClick={() => handleOnClick(<Flags.TC />)}/>,
 <Flags.TV onClick={() => handleOnClick(<Flags.TV />)}/>,
 <Flags.UG onClick={() => handleOnClick(<Flags.UG />)}/>,
 <Flags.UA onClick={() => handleOnClick(<Flags.UA />)}/>,
 <Flags.AE onClick={() => handleOnClick(<Flags.AE />)}/>,
 <Flags.GB onClick={() => handleOnClick(<Flags.GB />)}/>,
 <Flags.US onClick={() => handleOnClick(<Flags.US />)}/>,
 <Flags.UM onClick={() => handleOnClick(<Flags.UM />)}/>,
 <Flags.UY onClick={() => handleOnClick(<Flags.UY />)}/>,
 <Flags.UZ onClick={() => handleOnClick(<Flags.UZ />)}/>,
 <Flags.VU onClick={() => handleOnClick(<Flags.VU />)}/>,
 <Flags.VE onClick={() => handleOnClick(<Flags.VE />)}/>,
 <Flags.VN onClick={() => handleOnClick(<Flags.VN />)}/>,
 <Flags.VG onClick={() => handleOnClick(<Flags.VG />)}/>,
 <Flags.VI onClick={() => handleOnClick(<Flags.VI />)}/>,
 <Flags.WF onClick={() => handleOnClick(<Flags.WF />)}/>,
 <Flags.EH onClick={() => handleOnClick(<Flags.EH />)}/>,
 <Flags.YE onClick={() => handleOnClick(<Flags.YE />)}/>,
 <Flags.ZW onClick={() => handleOnClick(<Flags.ZW />)}/>,
 <Flags.ZM onClick={() => handleOnClick(<Flags.ZM />)}/>,
]

  flagComponents.sort((a, b) => 0.5 - Math.random());

  const handleOnClick = (component) => {
    onChange(component);
    setVisible(false);
  }

  const toggleVisibility = () => {
    setVisible(true)
  }

  var selectedFlag;
  if (value) {
    selectedFlag = React.cloneElement(
      value,
      { onClick: toggleVisibility }
    );
  }

  return (
      <section className={styles.countryPicker}>
      { !visible ?  // 
        ( // selected a flag
          selectedFlag ? selectedFlag // not yet selected a flag
        : <span onClick={toggleVisibility}>Select a country ▼</span>
        ) // render list of flags
       : <section className={styles.dropdownContainer}> 
        {flagComponents.map((x) => 
          x
        )};
      </section>
      }
      </section>
  )
}

const memoComponent = React.memo(CountryPicker);
export default memoComponent;